# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudaalmaty', '0003_comments_comment_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
