# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudaalmaty', '0005_auto_20180423_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Feedback',
        ),
    ]
