# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudaalmaty', '0011_auto_20180423_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comm',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comm',
            name='comm_place',
        ),
        migrations.RemoveField(
            model_name='review',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comm_place',
        ),
        migrations.DeleteModel(
            name='Comm',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
