# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('addr', models.TextField()),
                ('specialty', models.TextField()),
                ('cash', models.TextField()),
                ('schedule', models.TextField()),
                ('place_type', models.CharField(max_length=200)),
                ('first_photo', models.CharField(max_length=200)),
                ('second_photo', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
