# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almaty', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.TextField()),
            ],
        ),
    ]
